export const genres = [
  'Adventure',
  'Biography',
  "Children's",
  'Classic',
  'Cooking',
  'Dystopian',
  'Fantasy',
  'Geography',
  'Geopolitics',
  'Graphic Novel',
  'Historical Fiction',
  'Horror',
  'Mystery',
  'Non-Fiction',
  'Philosophy',
  'Poetry',
  'Romance',
  'Science Fiction',
  'Self-Help',
  'Thriller',
  'Travel',
  'Young Adult',
];
